#!/bin/sh

set -e

log() {
  echo "$(date -I'seconds') $1"
}

shutdown() {
  log "shutdown"
  /usr/sbin/postfix stop
  log "stopped postfix: exit-code=$?"
  exit 0
}

trap 'shutdown' HUP INT QUIT KILL TERM

postconf -e "smtp_sasl_password_maps = static:${SMTP_SASL_PASSWORD_MAPS}"
postconf -e "myhostname = ${MYHOSTNAME}"
postconf -e "mydestination = localhost, ${MYDESTINATION}"
postconf -e "myorigin = ${MYORIGIN}"
postconf -e "mynetworks = ${MYNETWORKS}"
postconf -e "relayhost = ${RELAYHOST}"
postconf -e "debug_peer_list = ${DEBUG_PEER_LIST}"

if [[ -n ${SENDER_CANONICAL_ADDRESS} ]]; then
  echo "/.*/    ${SENDER_CANONICAL_ADDRESS}" > /etc/postfix/sender_canonical
  echo "/^From:(.*)/ REPLACE From: <${SENDER_CANONICAL_ADDRESS}>" >  /etc/postfix/second_header_checks
  echo '/(.*)/  prepend X-Envelope-From: <$1>' > /etc/postfix/sender_access
  echo '/^From: (.*)/ PREPEND Reply-to: $1' > /etc/postfix/header_checks
fi

# run postfix
/usr/sbin/postfix start-fg 2>&1 | rg --line-buffered -v "${LOG_FILTER_REGEX:-"^$"}" &

wait ${!}
